### ISSUE TITLE
What is the relationship to ImageSharp?

### ISSUE THREAD

**Issue by brandscill** [iron-software/IronSoftware.System.Drawing#23]
Hi,

I am a little confused about the relationship to ImageSharp, I actually got an email from IronSoftware about this library being a free open source library, but it seems it also has a split license because of the reliance on ImageSharp.

Can someone explain why there is a dependency with ImageSharp and if that's the reason for the more restrictive licensing?

**Comment by michael-ironsoftware** [comment]
ImageSharp is a transitive NuGet dependency - that is the relationship. Imagesharp is open source and free for many, but not all users: 

Source: https://github.com/SixLabors/ImageSharp/blob/main/LICENSE#L34 (16 Dec 2022)

```
  Works in Source or Object form are licensed to You under the Apache License, Version 2.0 if.
  
 - You are consuming the Work in for use in software licensed under an Open Source or Source Available license.
   - You are consuming the Work as a Transitive Package Dependency.
   - You are consuming the Work as a Direct Package Dependency in the capacity of a For-profit company/individual with
     less than 1M USD annual gross revenue.
   - You are consuming the Work as a Direct Package Dependency in the capacity of a Non-profit organization
     or Registered Charity.
```

ImageSharp is free as a **Transitive Package Dependency** in an open source project. This is how our users will be implementing it in most cases - which applies the free and permissive Apache license to ImageSharp to their usage of image sharp. Most IronDrawing users will have ImageSharp as a  Transitive Package Dependency.

Package dependency tree:
- IronPdf
   - IronDrawing 
       - ImageSharp

E.g.   You reference IronDrawing in your product.  Then IronDrawing references  ImageSharp. A dependency of a dependency…a transitive dependency. So are licensed under the free Apache license.
