### ISSUE TITLE
converting from SIPSorceryMedia.Abstractions.RawImage to AnyBitmap

### ISSUE THREAD

**Issue by mail2mhossain** [iron-software/IronSoftware.System.Drawing#27]
I am trying to convert from SIPSorceryMedia.Abstractions.RawImage to AnyBitmap.

It can be converted to System.Drawing.Bitmap as follows:
System.Drawing.Bitmap bmpImage = new System.Drawing.Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, rawImage.Sample);

AnyBitmap bmpImage = new System.Drawing.Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, rawImage.Sample);

Now I want to convert it to directly to AnyBitmap from SIPSorceryMedia.Abstractions.RawImage

SIPSorceryMedia.Abstractions.RawImage -> https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/master/src/MediaEndPoints.cs
It has following properties:

    int Width
    int Height
    int Stride
    IntPtr Sample
    VideoPixelFormatsEnum PixelFormat -> https://github.com/sipsorcery-org/SIPSorceryMedia.Abstractions/blob/master/src/MediaEndPoints.cs

public enum VideoPixelFormatsEnum
{
Rgb,
Bgr,
Bgra,
I420,
NV12
}

**Comment by mail2mhossain** [comment]
RESPONSE FROM SIPSORCERY:

SIPSorceryMedia.Abstractions.RawImage contains all necessary info about an image in AV_PIX_FMT_BGR24 format (format in FFmpeg context)

So 8 bits for B, 8 bits for G, 8 bits for R (=> 24 bits for one pixel), it's size (width and height) and it's stride

As an example, This AV_PIX_FMT_BGR24 format is the same as this one [PixelFormat.Format24bppRgb](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.imaging.pixelformat?msclkid=7e0af028cf6311ecafd2a420650bef5f&view=dotnet-plat-ext-6.0) in
System.Drawing.Imaging context.

According the library, you must use an equivalent:

    use 8 bits for each colors
    no alpha
    necessary to specify width, height and stride

About stride, read this: https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.-ctor?view=dotnet-plat-ext-7.0#system-drawing-bitmap-ctor(system-int32-system-int32-system-int32-system-drawing-imaging-pixelformat-system-intptr)

**Comment by iron-production-team** [comment]
Can you explain clearly how you would achieve this via System.Drawing.Bitmap in the past and we can try to match that functionality.  

https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=windowsdesktop-7.0

Our aim is to help people migrate away from System.Drawing as it no longer supports non windows targets in .NET 6 and 7 .

**Comment by mail2mhossain** [comment]
**Working Code:**

private void _videoSource_OnVideoSourceRawSampleFaster (uint durationMilliseconds, SIPSorceryMedia.Abstractions.RawImage rawImage)
        {
            AnyBitmap bmpImage = new System.Drawing.Bitmap(rawImage.Width, rawImage.Height, rawImage.Stride, System.Drawing.Imaging.PixelFormat.Format24bppRgb, rawImage.Sample);

            FireUpdateVideoControlEvent(bmpImage, rawImage);
        }


**Not Working:**

private void _videoSource_OnVideoSourceRawSampleFaster (uint durationMilliseconds, SIPSorceryMedia.Abstractions.RawImage rawImage)
        {
            byte[] managedArray = new byte[rawImage.Height * rawImage.Stride];
            Marshal.Copy(rawImage.Sample, managedArray, 0, managedArray.Length);
            AnyBitmap bmpImage = AnyBitmap.FromBytes(managedArray);

            FireUpdateVideoControlEvent(bmpImage, rawImage);
        }


I have uploaded a test project. In "videoSource_OnVideoSourceRawSampleFaster" method of class "VideoCaptureDevice" has image conversion code.

**github link: https://github.com/mail2mhossain/RawImageToAnyBitmap.git 
PLEASE PUT "ffmpeg" folder under debug folder.**

[RawImageToAnyBitMap.zip](https://github.com/iron-software/IronSoftware.System.Drawing/files/10341162/RawImageToAnyBitMap.zip)

**Comment by mail2mhossain** [comment]
> 

Did you get the test project?

**Comment by mail2mhossain** [comment]
> Our aim is to help people migrate away from System.Drawing as it no longer supports non windows targets in .NET 6 and 7
> 
> SipSourcery is not a major image format library and we are unlikely to provide implicit Export methods to that format as a priority. But we do what you to be able to export the correct Bytes, Pixels or Stream to construct the custom image format your software uses.
> 
> Can you explain clearly again with a code example how you would achieve this binary export via System.Drawing.Bitmap in the past (by an isolated code example) and we can try to match that functionality.
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=windowsdesktop-7.0

Code Example: 
github link: https://github.com/mail2mhossain/RawImageToAnyBitmap.git
PLEASE PUT "ffmpeg" folder under debug folder.

[RawImageToAnyBitMap.zip](https://github.com/iron-software/IronSoftware.System.Drawing/files/10432343/RawImageToAnyBitMap.zip)

**Comment by michael-ironsoftware** [comment]
As mentioned before, a direct conversion from `AnyBitmap` from `SIPSorceryMedia.Abstractions.RawImage` and vice-versa is likely because SipSourcery is not a major image format library and we are unlikely to provide implicit Export methods to that format as a priority.
