### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by LanceMcCarthy** [iron-software/IronSoftware.System.Drawing#46]
Hi IronSoftware team, I don't see a license file in this repo. Can you please explain the licensing model you're using for Ironsoftware.System.Drawing`?

For example, in one of my repos you'll see a file named [LICENSE](https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/main/LICENSE), that contains one of the pre-written licenses from GitHub (specifically MIT in that case, but you're not restricted to it)

**Comment by michael-ironsoftware** [comment]
You may find the license here:
[LICENSE](https://github.com/iron-software/IronSoftware.System.Drawing/blob/master/NuGet/LICENSE.txt)

**Comment by LanceMcCarthy** [comment]
Thanks for the prompt follow up!
