### ISSUE TITLE
MissingMethodException when running with ImageSharp v3.0.0

### ISSUE THREAD

**Issue by natehitze** [iron-software/IronSoftware.System.Drawing#47]
We're getting the following exception after installing ImageSharp v3.0.0:

> System.MissingMethodException
> Method not found: 'Void SixLabors.ImageSharp.Formats.Bmp.BmpEncoder.set_BitsPerPixel(System.Nullable`1<SixLabors.ImageSharp.Formats.Bmp.BmpBitsPerPixel>)'.
>    at IronSoftware.Drawing.AnyBitmap.op_Implicit(Image`1 Image)
>    at IronBarCode.GeneratedBarcode.Render()
>    at IronBarCode.GeneratedBarcode.get_()
>    at IronBarCode.GeneratedBarcode.ToPngBinaryData()

This is with BarCode version 2023.3.2.

**Comment by michael-ironsoftware** [comment]
Hello @natehitze we are aware of this issue and working hard on a fix. Will update here once it's fixed.
