### ISSUE TITLE
CreateMultiFrameTiff creates Output Tiff with huge size

### ISSUE THREAD

**Issue by SanKumSan** [iron-software/IronSoftware.System.Drawing#57]
Using IronSoftware.Drawing to create multi frame tiff creates huge size output tiff file.

// sourceFiles = list of tiffs
var outputTiff = IronSoftware.Drawing.AnyBitmap.CreateMultiFrameTiff(sourceFiles);

Input tiff files sizes = each file is of 500KB (total of 2 files)
Output tiff size after merged >= 50MB

The compression present in the input tiff is lost when the output tiff is created and the compression is None.

How to get output merged tiff with compression same as input tiff and not having huge size?
Any fix in IronSoftware.Drawing or any work arounds are welcome.

Thanks

**Comment by artem-iron** [comment]
Hey there! Thanks a lot for bringing this to our attention! We'll investigate the issue and get back to you with an update.
