### ISSUE TITLE
spelling issue in AnyBitmap .ctor

### ISSUE THREAD

**Issue by mwwhited** [iron-software/IronSoftware.System.Drawing#91]
https://github.com/iron-software/IronSoftware.System.Drawing/blob/6af48e371c46a8da65f9ea73a51b9f2efba0a3e2/IronSoftware.Drawing/IronSoftware.Drawing.Common/AnyBitmap.cs#L571

the parameter `backgrounColor` should be `backgroundColor`

**Comment by artem-iron** [comment]
Thank you for noticing @mwwhited
